
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data  # Volume partagé pour le répertoire /data
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

